[tool.mypy]
mypy_path = "./stubs/"

python_version = 3.9

ignore_missing_imports = false

disallow_any_generics = true

disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true

no_implicit_optional = true
strict_optional = true

warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true

show_none_errors = true
ignore_errors = false

allow_untyped_globals = false
allow_redefinition = false
implicit_reexport = false
strict_equality = true

show_error_context = false
show_column_numbers = true
show_error_codes = true
color_output = true
error_summary = true
pretty = true

[[tool.mypy.overrides]]
module="tqdm.*"
ignore_errors = true
