from tensorflow import keras
from typing import Any

class TqdmCallback(keras.callbacks.Callback):
    @staticmethod
    def bar2callback(bar, pop: Any | None = ..., delta=...): ...
    tqdm_class: Any
    epoch_bar: Any
    on_epoch_end: Any
    batches: Any
    verbose: Any
    batch_bar: Any
    on_batch_end: Any
    def __init__(self, epochs: Any | None = ..., data_size: Any | None = ..., batch_size: Any | None = ..., verbose: int = ..., tqdm_class=..., **tqdm_kwargs): ...
    def on_train_begin(self, *_, **__) -> None: ...
    def on_epoch_begin(self, epoch, *_, **__): ...
    def on_train_end(self, *_, **__) -> None: ...
    def display(self) -> None: ...
