from .std import tqdm as std_tqdm
from IPython.html.widgets import ContainerWidget as HBox
from typing import Any

HBox = object

class TqdmHBox(HBox): ...

class tqdm_notebook(std_tqdm):
    @staticmethod
    def status_printer(_, total: Any | None = ..., desc: Any | None = ..., ncols: Any | None = ...): ...
    displayed: bool
    def display(self, msg: Any | None = ..., pos: Any | None = ..., close: bool = ..., bar_style: Any | None = ..., check_delay: bool = ...) -> None: ...
    @property
    def colour(self): ...
    @colour.setter
    def colour(self, bar_color) -> None: ...
    disp: Any
    ncols: Any
    container: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self): ...
    def update(self, n: int = ...): ...
    def close(self) -> None: ...
    def clear(self, *_, **__) -> None: ...
    def reset(self, total: Any | None = ...): ...

def tnrange(*args, **kwargs): ...
tqdm = tqdm_notebook
trange = tnrange
