from .std import tqdm as std_tqdm
from rich.progress import ProgressColumn
from typing import Any

class FractionColumn(ProgressColumn):
    unit_scale: Any
    unit_divisor: Any
    def __init__(self, unit_scale: bool = ..., unit_divisor: int = ...) -> None: ...
    def render(self, task): ...

class RateColumn(ProgressColumn):
    unit: Any
    unit_scale: Any
    unit_divisor: Any
    def __init__(self, unit: str = ..., unit_scale: bool = ..., unit_divisor: int = ...) -> None: ...
    def render(self, task): ...

class tqdm_rich(std_tqdm):
    def __init__(self, *args, **kwargs) -> None: ...
    def close(self) -> None: ...
    def clear(self, *_, **__) -> None: ...
    def display(self, *_, **__) -> None: ...
    def reset(self, total: Any | None = ...) -> None: ...

def trrange(*args, **kwargs): ...
tqdm = tqdm_rich
trange = trrange
