from ..auto import tqdm as tqdm_auto
from .utils_worker import MonoWorker
from typing import Any

class TelegramIO(MonoWorker):
    API: str
    token: Any
    chat_id: Any
    session: Any
    text: Any
    def __init__(self, token, chat_id) -> None: ...
    @property
    def message_id(self): ...
    def write(self, s): ...
    def delete(self): ...

class tqdm_telegram(tqdm_auto):
    tgio: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def display(self, **kwargs) -> None: ...
    def clear(self, *args, **kwargs) -> None: ...
    def close(self) -> None: ...

def ttgrange(*args, **kwargs): ...
tqdm = tqdm_telegram
trange = ttgrange
